DROP DATABASE IF EXISTS Instituto;
CREATE DATABASE Instituto;
USE Instituto;

CREATE TABLE Actual(
NumExp INT NOT NULL AUTO_INCREMENT,
DNI VARCHAR(9) NULL,
Nombre VARCHAR(30) NOT NULL,
Apellido1 VARCHAR(50) NOT NULL,
Apellido2 VARCHAR(50) NULL,
Direccion VARCHAR(100) NOT NULL,
FecNac DATE NOT NULL,
Curso VARCHAR(5) NOT NULL,
FecAlta TIMESTAMP NOT NULL,
FecMod TIMESTAMP NULL,
FecBaja TIMESTAMP NULL,
Motivo VARCHAR(500) NULL,
Obs VARCHAR(1000) NULL,
PRIMARY KEY (NumExp),
UNIQUE (DNI)
);

CREATE TABLE Historico(
ID INT NOT NULL AUTO_INCREMENT,
NumExp INT NOT NULL,
DNI VARCHAR(9) NULL,
Nombre VARCHAR(30) NOT NULL,
Apellido1 VARCHAR(50) NOT NULL,
Apellido2 VARCHAR(50) NULL,
Direccion VARCHAR(100) NOT NULL,
FecNac DATE NOT NULL,
Curso VARCHAR(5) NOT NULL,
FecAlta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
FecMod TIMESTAMP NULL,
FecBaja TIMESTAMP NULL,
Motivo VARCHAR(500) NULL,
Obs VARCHAR(1000) NULL,
PRIMARY KEY (ID)
);